-- PowerDesigner 16.5 reverse engineering source
-- Generated by tools/export_powerdesigner_schema.py
-- Source database: test18
-- Scope: public.dtlms_* tables excluding dtlms_runtime_* and dtlms_schema_migrations

SET client_encoding = 'UTF8';

-- Table: public.dtlms_achievements
CREATE TABLE public."dtlms_achievements" (
    "id" bigint DEFAULT nextval('dtlms_achievements_id_seq'::regclass) NOT NULL,
    "student_id" bigint NOT NULL,
    "achievement_type" character varying(32) NOT NULL,
    "title" character varying(255) NOT NULL,
    "published_at" date,
    "publisher_name" character varying(255),
    "ranking_text" character varying(64),
    "is_deleted" boolean DEFAULT false NOT NULL,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_achievements_pkey" PRIMARY KEY (id)
);

-- Table: public.dtlms_admission_decisions
CREATE TABLE public."dtlms_admission_decisions" (
    "id" bigint DEFAULT nextval('dtlms_admission_decisions_id_seq'::regclass) NOT NULL,
    "application_id" bigint NOT NULL,
    "decision_status" character varying(32) DEFAULT 'pending'::character varying NOT NULL,
    "rank_no" integer,
    "final_score" numeric(5,2),
    "transfer_option" character varying(64),
    "decision_comment" text,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_admission_decisions_pkey" PRIMARY KEY (id)
);

-- Table: public.dtlms_advisors
CREATE TABLE public."dtlms_advisors" (
    "id" bigint DEFAULT nextval('dtlms_advisors_id_seq'::regclass) NOT NULL,
    "advisor_no" character varying(32) NOT NULL,
    "full_name" character varying(128) NOT NULL,
    "title" character varying(64) NOT NULL,
    "organization_name" character varying(128) NOT NULL,
    "research_direction" character varying(255) NOT NULL,
    "annual_quota" integer DEFAULT 0 NOT NULL,
    "is_deleted" boolean DEFAULT false NOT NULL,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "user_id" bigint,
    CONSTRAINT "dtlms_advisors_pkey" PRIMARY KEY (id),
    CONSTRAINT "dtlms_advisors_advisor_no_key" UNIQUE (advisor_no)
);

-- Table: public.dtlms_application_materials
CREATE TABLE public."dtlms_application_materials" (
    "id" bigint DEFAULT nextval('dtlms_application_materials_id_seq'::regclass) NOT NULL,
    "application_id" bigint NOT NULL,
    "material_type" character varying(64) NOT NULL,
    "material_status" character varying(32) DEFAULT 'pending'::character varying NOT NULL,
    "file_url" character varying(255) NOT NULL,
    "is_deleted" boolean DEFAULT false NOT NULL,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_application_materials_pkey" PRIMARY KEY (id)
);

-- Table: public.dtlms_audit_policies
CREATE TABLE public."dtlms_audit_policies" (
    "id" bigint NOT NULL,
    "item" character varying(128) NOT NULL,
    "policy" text NOT NULL,
    "status" character varying(32) DEFAULT '启用'::character varying NOT NULL,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "is_deleted" boolean DEFAULT false NOT NULL,
    CONSTRAINT "dtlms_audit_policies_pkey" PRIMARY KEY (id)
);

-- Table: public.dtlms_background_assessments
CREATE TABLE public."dtlms_background_assessments" (
    "id" bigint DEFAULT nextval('dtlms_background_assessments_id_seq'::regclass) NOT NULL,
    "application_id" bigint NOT NULL,
    "evaluator_user_id" bigint,
    "evaluator_username" character varying(64) NOT NULL,
    "evaluator_name" character varying(128),
    "evaluator_role_code" character varying(64) NOT NULL,
    "assessment_result" character varying(32) NOT NULL,
    "assessment_comment" text,
    "assessed_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_background_assessments_pkey" PRIMARY KEY (id),
    CONSTRAINT "dtlms_background_assessments_application_id_evaluator_usern_key" UNIQUE (application_id, evaluator_username)
);

-- Table: public.dtlms_data_sync_logs
CREATE TABLE public."dtlms_data_sync_logs" (
    "id" bigint DEFAULT nextval('dtlms_data_sync_logs_id_seq'::regclass) NOT NULL,
    "source_system" character varying(64) NOT NULL,
    "target_system" character varying(64) NOT NULL,
    "sync_status" character varying(32) NOT NULL,
    "record_count" integer DEFAULT 0 NOT NULL,
    "failure_reason" text,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_data_sync_logs_pkey" PRIMARY KEY (id)
);

-- Table: public.dtlms_dict_data
CREATE TABLE public."dtlms_dict_data" (
    "id" bigint DEFAULT nextval('dtlms_dict_data_id_seq'::regclass) NOT NULL,
    "dict_type_id" bigint NOT NULL,
    "dict_type" character varying(100) NOT NULL,
    "label" character varying(100) NOT NULL,
    "value" character varying(100) NOT NULL,
    "sort_order" integer DEFAULT 0 NOT NULL,
    "status" character varying(32) DEFAULT '启用'::character varying NOT NULL,
    "color_type" character varying(32),
    "css_class" character varying(128),
    "remark" text,
    "is_deleted" boolean DEFAULT false NOT NULL,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_dict_data_pkey" PRIMARY KEY (id),
    CONSTRAINT "dtlms_dict_data_dict_type_value_key" UNIQUE (dict_type, value)
);

-- Table: public.dtlms_dict_types
CREATE TABLE public."dtlms_dict_types" (
    "id" bigint DEFAULT nextval('dtlms_dict_types_id_seq'::regclass) NOT NULL,
    "dict_name" character varying(100) NOT NULL,
    "dict_type" character varying(100) NOT NULL,
    "status" character varying(32) DEFAULT '启用'::character varying NOT NULL,
    "remark" text,
    "is_deleted" boolean DEFAULT false NOT NULL,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_dict_types_pkey" PRIMARY KEY (id),
    CONSTRAINT "dtlms_dict_types_dict_type_key" UNIQUE (dict_type)
);

-- Table: public.dtlms_integrations
CREATE TABLE public."dtlms_integrations" (
    "id" bigint NOT NULL,
    "name" character varying(128) NOT NULL,
    "direction" character varying(64) NOT NULL,
    "cadence" character varying(64) NOT NULL,
    "status" character varying(32) DEFAULT '正常'::character varying NOT NULL,
    "owner" character varying(128) DEFAULT ''::character varying NOT NULL,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "is_deleted" boolean DEFAULT false NOT NULL,
    CONSTRAINT "dtlms_integrations_pkey" PRIMARY KEY (id)
);

-- Table: public.dtlms_interview_groups
CREATE TABLE public."dtlms_interview_groups" (
    "id" bigint DEFAULT nextval('dtlms_interview_groups_id_seq'::regclass) NOT NULL,
    "plan_id" bigint NOT NULL,
    "group_code" character varying(64) NOT NULL,
    "group_name" character varying(128) NOT NULL,
    "interview_mode" character varying(32) DEFAULT 'offline'::character varying NOT NULL,
    "is_deleted" boolean DEFAULT false NOT NULL,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_interview_groups_pkey" PRIMARY KEY (id),
    CONSTRAINT "dtlms_interview_groups_plan_id_group_code_key" UNIQUE (plan_id, group_code)
);

-- Table: public.dtlms_interview_schedules
CREATE TABLE public."dtlms_interview_schedules" (
    "id" bigint DEFAULT nextval('dtlms_interview_schedules_id_seq'::regclass) NOT NULL,
    "application_id" bigint NOT NULL,
    "interview_group_id" bigint NOT NULL,
    "admission_ticket_no" character varying(64) NOT NULL,
    "starts_at" timestamp(6) with time zone NOT NULL,
    "ends_at" timestamp(6) with time zone NOT NULL,
    "schedule_status" character varying(32) DEFAULT 'scheduled'::character varying NOT NULL,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_interview_schedules_pkey" PRIMARY KEY (id),
    CONSTRAINT "dtlms_interview_schedules_admission_ticket_no_key" UNIQUE (admission_ticket_no)
);

-- Table: public.dtlms_interview_scores
CREATE TABLE public."dtlms_interview_scores" (
    "id" bigint DEFAULT nextval('dtlms_interview_scores_id_seq'::regclass) NOT NULL,
    "schedule_id" bigint NOT NULL,
    "evaluator_username" character varying(64) NOT NULL,
    "single_choice_score" numeric(5,2),
    "fill_blank_score" numeric(5,2),
    "coding_score" numeric(5,2),
    "interview_score" numeric(5,2),
    "ideological_score" numeric(5,2),
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_interview_scores_pkey" PRIMARY KEY (id)
);

-- Table: public.dtlms_login_logs
CREATE TABLE public."dtlms_login_logs" (
    "id" bigint DEFAULT nextval('dtlms_login_logs_id_seq'::regclass) NOT NULL,
    "username" character varying(64) NOT NULL,
    "login_status" character varying(32) NOT NULL,
    "login_ip" character varying(64),
    "user_agent" text,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_login_logs_pkey" PRIMARY KEY (id)
);

-- Table: public.dtlms_material_scores
CREATE TABLE public."dtlms_material_scores" (
    "id" bigint DEFAULT nextval('dtlms_material_scores_id_seq'::regclass) NOT NULL,
    "application_id" bigint NOT NULL,
    "reviewer_assignment_id" bigint NOT NULL,
    "material_score" numeric(5,2),
    "recommendation_text" text,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_material_scores_pkey" PRIMARY KEY (id)
);

-- Table: public.dtlms_notification_delivery_logs
CREATE TABLE public."dtlms_notification_delivery_logs" (
    "id" bigint DEFAULT nextval('dtlms_notification_delivery_logs_id_seq'::regclass) NOT NULL,
    "channel" character varying(32) NOT NULL,
    "template_code" character varying(64),
    "recipient" character varying(255) NOT NULL,
    "subject" character varying(255) NOT NULL,
    "send_status" character varying(32) NOT NULL,
    "failure_reason" text,
    "business_key" character varying(64),
    "triggered_by" character varying(64),
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_notification_delivery_logs_pkey" PRIMARY KEY (id)
);

-- Table: public.dtlms_notification_templates
CREATE TABLE public."dtlms_notification_templates" (
    "id" bigint DEFAULT nextval('dtlms_notification_templates_id_seq'::regclass) NOT NULL,
    "template_code" character varying(64) NOT NULL,
    "channel" character varying(32) NOT NULL,
    "title" character varying(128) NOT NULL,
    "content_template" text NOT NULL,
    "variables_schema" jsonb,
    "is_deleted" boolean DEFAULT false NOT NULL,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_notification_templates_pkey" PRIMARY KEY (id),
    CONSTRAINT "dtlms_notification_templates_template_code_key" UNIQUE (template_code)
);

-- Table: public.dtlms_operation_logs
CREATE TABLE public."dtlms_operation_logs" (
    "id" bigint DEFAULT nextval('dtlms_operation_logs_id_seq'::regclass) NOT NULL,
    "operator_username" character varying(64) NOT NULL,
    "operator_role" character varying(64) NOT NULL,
    "module_name" character varying(64) NOT NULL,
    "entity_name" character varying(64) NOT NULL,
    "entity_id" character varying(64) NOT NULL,
    "action" character varying(32) NOT NULL,
    "old_value" jsonb,
    "new_value" jsonb,
    "request_ip" character varying(64),
    "result" character varying(32) DEFAULT 'success'::character varying NOT NULL,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_operation_logs_pkey" PRIMARY KEY (id)
);

-- Table: public.dtlms_outbound_studies
CREATE TABLE public."dtlms_outbound_studies" (
    "id" bigint DEFAULT nextval('dtlms_outbound_studies_id_seq'::regclass) NOT NULL,
    "student_id" bigint NOT NULL,
    "advisor_id" bigint NOT NULL,
    "study_type" character varying(64) NOT NULL,
    "destination" character varying(128) NOT NULL,
    "start_date" date NOT NULL,
    "end_date" date NOT NULL,
    "approval_status" character varying(32) DEFAULT 'submitted'::character varying NOT NULL,
    "expected_outcome" text,
    "is_deleted" boolean DEFAULT false NOT NULL,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "business_key" character varying(64) NOT NULL,
    CONSTRAINT "dtlms_outbound_studies_pkey" PRIMARY KEY (id)
);

-- Table: public.dtlms_permissions
CREATE TABLE public."dtlms_permissions" (
    "id" bigint DEFAULT nextval('dtlms_permissions_id_seq'::regclass) NOT NULL,
    "permission_code" character varying(128) NOT NULL,
    "permission_name" character varying(128) NOT NULL,
    "module_name" character varying(64) NOT NULL,
    "is_deleted" boolean DEFAULT false NOT NULL,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_permissions_pkey" PRIMARY KEY (id),
    CONSTRAINT "dtlms_permissions_permission_code_key" UNIQUE (permission_code)
);

-- Table: public.dtlms_portal_application_achievement_records
CREATE TABLE public."dtlms_portal_application_achievement_records" (
    "id" bigint DEFAULT nextval('dtlms_portal_application_achievement_records_id_seq'::regclass) NOT NULL,
    "application_id" bigint NOT NULL,
    "achievement_type" character varying(32) NOT NULL,
    "paper_title" character varying(255),
    "author_order" character varying(32),
    "journal_or_conference" character varying(255),
    "publish_or_index_month" character varying(16),
    "award_name" character varying(255),
    "awarding_organization" character varying(255),
    "award_level" character varying(128),
    "award_year" character varying(16),
    "responsibility_text" text,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "achievement_month" character varying(16),
    "award_rank" character varying(64),
    "award_certificate_attachment_url" character varying(512),
    "description_text" text,
    CONSTRAINT "dtlms_portal_application_achievement_records_pkey" PRIMARY KEY (id)
);

-- Table: public.dtlms_portal_application_attachments
CREATE TABLE public."dtlms_portal_application_attachments" (
    "id" bigint DEFAULT nextval('dtlms_portal_application_attachments_id_seq'::regclass) NOT NULL,
    "portal_student_id" bigint,
    "application_id" bigint,
    "owner_type" character varying(64) NOT NULL,
    "owner_id" bigint,
    "attachment_category" character varying(64) NOT NULL,
    "file_name" character varying(255) NOT NULL,
    "file_url" text NOT NULL,
    "file_type" character varying(32),
    "file_size" bigint,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_portal_application_attachments_pkey" PRIMARY KEY (id)
);

-- Table: public.dtlms_portal_application_declarations
CREATE TABLE public."dtlms_portal_application_declarations" (
    "application_id" bigint NOT NULL,
    "has_read_declaration" boolean DEFAULT false NOT NULL,
    "declaration_text" text,
    "progress_snapshot" jsonb,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_portal_application_declarations_pkey" PRIMARY KEY (application_id)
);

-- Table: public.dtlms_portal_application_education_experiences
CREATE TABLE public."dtlms_portal_application_education_experiences" (
    "id" bigint DEFAULT nextval('dtlms_portal_application_education_experiences_id_seq'::regclass) NOT NULL,
    "application_id" bigint NOT NULL,
    "sort_order" integer DEFAULT 1 NOT NULL,
    "education_stage" character varying(64) NOT NULL,
    "start_month" character varying(16),
    "end_month" character varying(16),
    "school_name" character varying(255) NOT NULL,
    "major_name" character varying(255),
    "average_score" character varying(64),
    "gpa" character varying(32),
    "ranking" character varying(64),
    "verifier_name" character varying(128),
    "verifier_phone" character varying(32),
    "transcript_attachment_url" text,
    "degree_certificate_attachment_url" text,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "graduation_certificate_attachment_url" text,
    CONSTRAINT "dtlms_portal_application_education_experiences_pkey" PRIMARY KEY (id)
);

-- Table: public.dtlms_portal_application_english_proficiencies
CREATE TABLE public."dtlms_portal_application_english_proficiencies" (
    "id" bigint DEFAULT nextval('dtlms_portal_application_english_proficiencies_id_seq'::regclass) NOT NULL,
    "application_id" bigint NOT NULL,
    "exam_name" character varying(32) NOT NULL,
    "score_text" character varying(64) NOT NULL,
    "certificate_attachment_url" text,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_portal_application_english_proficiencies_pkey" PRIMARY KEY (id)
);

-- Table: public.dtlms_portal_application_family_members
CREATE TABLE public."dtlms_portal_application_family_members" (
    "id" bigint DEFAULT nextval('dtlms_portal_application_family_members_id_seq'::regclass) NOT NULL,
    "application_id" bigint NOT NULL,
    "member_name" character varying(64) NOT NULL,
    "relation_type" character varying(16) NOT NULL,
    "employer_name" character varying(255),
    "job_title" character varying(128),
    "contact_phone" character varying(32),
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_portal_application_family_members_pkey" PRIMARY KEY (id)
);

-- Table: public.dtlms_portal_application_personal_statements
CREATE TABLE public."dtlms_portal_application_personal_statements" (
    "application_id" bigint NOT NULL,
    "personal_statement_text" text,
    "ai_problem_statement" text,
    "ai_industry_opinion" text,
    "resume_attachment_url" text,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "growth_experience_text" text,
    "program_application_reason_text" text,
    "career_plan_text" text,
    "supporting_material_attachment_url" text,
    CONSTRAINT "dtlms_portal_application_personal_statements_pkey" PRIMARY KEY (application_id)
);

-- Table: public.dtlms_portal_application_practice_experiences
CREATE TABLE public."dtlms_portal_application_practice_experiences" (
    "id" bigint DEFAULT nextval('dtlms_portal_application_practice_experiences_id_seq'::regclass) NOT NULL,
    "application_id" bigint NOT NULL,
    "start_month" character varying(16),
    "end_month" character varying(16),
    "organization_name" character varying(255) NOT NULL,
    "position_name" character varying(128),
    "responsibility_text" text,
    "verifier_name" character varying(128),
    "verifier_phone" character varying(32),
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_portal_application_practice_experiences_pkey" PRIMARY KEY (id)
);

-- Table: public.dtlms_portal_application_preferences
CREATE TABLE public."dtlms_portal_application_preferences" (
    "id" bigint DEFAULT nextval('dtlms_portal_application_preferences_id_seq'::regclass) NOT NULL,
    "application_id" bigint NOT NULL,
    "preference_order" integer NOT NULL,
    "research_center_name" character varying(128),
    "advisor_name" character varying(128),
    "is_optional" boolean DEFAULT false NOT NULL,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "team_id" bigint,
    "advisor_user_id" bigint,
    CONSTRAINT "dtlms_portal_application_preferences_pkey" PRIMARY KEY (id),
    CONSTRAINT "uq_portal_application_preferences_order" UNIQUE (application_id, preference_order)
);

-- Table: public.dtlms_portal_student_profiles
CREATE TABLE public."dtlms_portal_student_profiles" (
    "portal_student_id" bigint NOT NULL,
    "full_name_pinyin" character varying(128),
    "gender" character varying(16),
    "birth_date" character varying(32),
    "ethnic_group" character varying(64),
    "native_place" character varying(128),
    "political_status" character varying(64),
    "marital_status" character varying(32),
    "religious_belief" character varying(128),
    "id_type" character varying(64),
    "mailing_address" text,
    "emergency_contact_name" character varying(128),
    "emergency_contact_phone" character varying(32),
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "profile_photo_url" character varying(255),
    "id_card_collage_url" character varying(255),
    CONSTRAINT "dtlms_portal_student_profiles_pkey" PRIMARY KEY (portal_student_id)
);

-- Table: public.dtlms_portal_students
CREATE TABLE public."dtlms_portal_students" (
    "id" bigint DEFAULT nextval('dtlms_portal_students_id_seq'::regclass) NOT NULL,
    "full_name" character varying(128) NOT NULL,
    "phone_number" character varying(32) NOT NULL,
    "email" character varying(128) NOT NULL,
    "id_number" character varying(64) NOT NULL,
    "graduation_school" character varying(255),
    "highest_degree" character varying(64),
    "intended_field" character varying(128),
    "political_status" character varying(64),
    "selected_plan_id" bigint,
    "selected_team_name" character varying(128),
    "selected_advisor_name" character varying(128),
    "self_evaluation" text,
    "submitted_at" timestamp(6) with time zone,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "password_hash" character varying(255),
    "gender" character varying(16),
    "birth_date" character varying(32),
    "ethnic_group" character varying(64),
    "native_place" character varying(128),
    "marital_status" character varying(32),
    "religious_belief" character varying(128),
    "id_type" character varying(64),
    "mailing_address" text,
    "english_level" character varying(128),
    "family_info" text,
    "education_experience" text,
    "practice_experience" text,
    "personal_profile" text,
    "recommendation_notes" text,
    "personal_statement_text" text,
    "signed_agreement" boolean DEFAULT false NOT NULL,
    "account_status" character varying(32) DEFAULT '启用'::character varying NOT NULL,
    "application_draft" jsonb,
    "selected_team_id" bigint,
    "selected_advisor_user_id" bigint,
    CONSTRAINT "dtlms_portal_students_pkey" PRIMARY KEY (id),
    CONSTRAINT "dtlms_portal_students_email_key" UNIQUE (email),
    CONSTRAINT "dtlms_portal_students_id_number_key" UNIQUE (id_number),
    CONSTRAINT "dtlms_portal_students_phone_number_key" UNIQUE (phone_number)
);

-- Table: public.dtlms_qualification_reviews
CREATE TABLE public."dtlms_qualification_reviews" (
    "id" bigint DEFAULT nextval('dtlms_qualification_reviews_id_seq'::regclass) NOT NULL,
    "application_id" bigint NOT NULL,
    "reviewer_username" character varying(64) NOT NULL,
    "review_status" character varying(32) DEFAULT 'pending'::character varying NOT NULL,
    "review_comment" text,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_qualification_reviews_pkey" PRIMARY KEY (id)
);

-- Table: public.dtlms_recruitment_applications
CREATE TABLE public."dtlms_recruitment_applications" (
    "id" bigint DEFAULT nextval('dtlms_recruitment_applications_id_seq'::regclass) NOT NULL,
    "plan_id" bigint NOT NULL,
    "student_name" character varying(128) NOT NULL,
    "candidate_no" character varying(64) NOT NULL,
    "gender" character varying(16) NOT NULL,
    "graduation_school" character varying(255),
    "highest_degree" character varying(64),
    "intended_field_id" bigint,
    "application_status" character varying(32) DEFAULT 'submitted'::character varying NOT NULL,
    "is_deleted" boolean DEFAULT false NOT NULL,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "business_key" character varying(64) NOT NULL,
    "review_round" character varying(64),
    "first_choice" character varying(255),
    "second_choice" character varying(255),
    "political_status" character varying(64),
    "marital_status" character varying(32),
    "religious_belief" character varying(128),
    "native_place" character varying(128),
    "phone_number" character varying(64),
    "email" character varying(255),
    "mailing_address" text,
    "id_type" character varying(64),
    "id_number" character varying(128),
    "undergraduate_school" character varying(255),
    "accept_adjustment" character varying(16),
    "undergraduate_average_score" character varying(64),
    "undergraduate_gpa" character varying(64),
    "undergraduate_rank" character varying(64),
    "undergraduate_major" character varying(255),
    "graduate_average_score" character varying(64),
    "graduate_gpa" character varying(64),
    "graduate_rank" character varying(64),
    "graduate_major" character varying(255),
    "intended_advisor_name" character varying(128),
    "discovery_channel" text,
    "graduate_school" character varying(255),
    "overseas_university_name" character varying(255),
    "overseas_master_university_name" character varying(255),
    "self_evaluation" text,
    "applied_at" timestamp(6) with time zone,
    "research_problem" text,
    "research_status_analysis" text,
    "research_impact" text,
    "ai_society_impact" text,
    "dissenting_view" text,
    "family_info" text,
    "education_experience" text,
    "practice_experience" text,
    "personal_statement_text" text,
    "student_activity_experience" text,
    "personal_statement_attachment" text,
    "material_list_attachment" text,
    "supplementary_profile" text,
    "portal_student_id" bigint,
    "source_channel" character varying(64),
    "source_channel_other" character varying(255),
    "first_choice_team_id" bigint,
    "second_choice_team_id" bigint,
    "intended_advisor_user_id" bigint,
    CONSTRAINT "dtlms_recruitment_applications_pkey" PRIMARY KEY (id),
    CONSTRAINT "dtlms_recruitment_applications_candidate_no_key" UNIQUE (candidate_no)
);

-- Table: public.dtlms_recruitment_plans
CREATE TABLE public."dtlms_recruitment_plans" (
    "id" bigint DEFAULT nextval('dtlms_recruitment_plans_id_seq'::regclass) NOT NULL,
    "plan_code" character varying(64) NOT NULL,
    "plan_name" character varying(255) NOT NULL,
    "academic_year" character varying(16) NOT NULL,
    "semester" character varying(16) NOT NULL,
    "start_date" timestamp(6) with time zone NOT NULL,
    "end_date" timestamp(6) with time zone NOT NULL,
    "target_quota" integer DEFAULT 0 NOT NULL,
    "plan_status" character varying(32) DEFAULT 'draft'::character varying NOT NULL,
    "is_deleted" boolean DEFAULT false NOT NULL,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "brochure_image_url" character varying(255),
    "plan_description" text,
    CONSTRAINT "dtlms_recruitment_plans_pkey" PRIMARY KEY (id),
    CONSTRAINT "dtlms_recruitment_plans_plan_code_key" UNIQUE (plan_code)
);

-- Table: public.dtlms_research_fields
CREATE TABLE public."dtlms_research_fields" (
    "id" bigint DEFAULT nextval('dtlms_research_fields_id_seq'::regclass) NOT NULL,
    "field_code" character varying(64) NOT NULL,
    "field_name" character varying(128) NOT NULL,
    "description" text,
    "is_deleted" boolean DEFAULT false NOT NULL,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_research_fields_pkey" PRIMARY KEY (id),
    CONSTRAINT "dtlms_research_fields_field_code_key" UNIQUE (field_code)
);

-- Table: public.dtlms_research_projects
CREATE TABLE public."dtlms_research_projects" (
    "id" bigint DEFAULT nextval('dtlms_research_projects_id_seq'::regclass) NOT NULL,
    "project_code" character varying(64) NOT NULL,
    "project_name" character varying(255) NOT NULL,
    "principal_advisor_id" bigint,
    "funding_amount" numeric(12,2),
    "is_deleted" boolean DEFAULT false NOT NULL,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_research_projects_pkey" PRIMARY KEY (id),
    CONSTRAINT "dtlms_research_projects_project_code_key" UNIQUE (project_code)
);

-- Table: public.dtlms_reviewer_assignments
CREATE TABLE public."dtlms_reviewer_assignments" (
    "id" bigint DEFAULT nextval('dtlms_reviewer_assignments_id_seq'::regclass) NOT NULL,
    "application_id" bigint NOT NULL,
    "reviewer_username" character varying(64) NOT NULL,
    "reviewer_role" character varying(32) NOT NULL,
    "assignment_status" character varying(32) DEFAULT 'assigned'::character varying NOT NULL,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_reviewer_assignments_pkey" PRIMARY KEY (id)
);

-- Table: public.dtlms_role_permissions
CREATE TABLE public."dtlms_role_permissions" (
    "id" bigint DEFAULT nextval('dtlms_role_permissions_id_seq'::regclass) NOT NULL,
    "role_id" bigint NOT NULL,
    "permission_id" bigint NOT NULL,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_role_permissions_pkey" PRIMARY KEY (id),
    CONSTRAINT "dtlms_role_permissions_role_id_permission_id_key" UNIQUE (role_id, permission_id)
);

-- Table: public.dtlms_roles
CREATE TABLE public."dtlms_roles" (
    "id" bigint DEFAULT nextval('dtlms_roles_id_seq'::regclass) NOT NULL,
    "role_code" character varying(64) NOT NULL,
    "role_name" character varying(128) NOT NULL,
    "description" text,
    "is_deleted" boolean DEFAULT false NOT NULL,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "scope_name" character varying(128) DEFAULT '系统管理'::character varying NOT NULL,
    CONSTRAINT "dtlms_roles_pkey" PRIMARY KEY (id),
    CONSTRAINT "dtlms_roles_role_code_key" UNIQUE (role_code)
);

-- Table: public.dtlms_scientific_reports
CREATE TABLE public."dtlms_scientific_reports" (
    "id" bigint DEFAULT nextval('dtlms_scientific_reports_id_seq'::regclass) NOT NULL,
    "student_id" bigint NOT NULL,
    "training_plan_id" bigint NOT NULL,
    "period_label" character varying(32) NOT NULL,
    "report_status" character varying(32) DEFAULT 'pending'::character varying NOT NULL,
    "summary" text NOT NULL,
    "attachment_url" character varying(255),
    "reviewer_advisor_id" bigint,
    "review_score" numeric(5,2),
    "review_comment" text,
    "is_deleted" boolean DEFAULT false NOT NULL,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "business_key" character varying(64) NOT NULL,
    CONSTRAINT "dtlms_scientific_reports_pkey" PRIMARY KEY (id)
);

-- Table: public.dtlms_student_advisor_history
CREATE TABLE public."dtlms_student_advisor_history" (
    "id" bigint DEFAULT nextval('dtlms_student_advisor_history_id_seq'::regclass) NOT NULL,
    "student_id" bigint NOT NULL,
    "advisor_id" bigint NOT NULL,
    "relation_type" character varying(32) DEFAULT 'primary'::character varying NOT NULL,
    "start_date" date NOT NULL,
    "end_date" date,
    "change_reason" text,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_student_advisor_history_pkey" PRIMARY KEY (id)
);

-- Table: public.dtlms_student_team_history
CREATE TABLE public."dtlms_student_team_history" (
    "id" bigint DEFAULT nextval('dtlms_student_team_history_id_seq'::regclass) NOT NULL,
    "student_id" bigint NOT NULL,
    "team_id" bigint NOT NULL,
    "start_date" date NOT NULL,
    "end_date" date,
    "change_reason" text,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_student_team_history_pkey" PRIMARY KEY (id)
);

-- Table: public.dtlms_students
CREATE TABLE public."dtlms_students" (
    "id" bigint DEFAULT nextval('dtlms_students_id_seq'::regclass) NOT NULL,
    "student_no" character varying(32) NOT NULL,
    "full_name" character varying(128) NOT NULL,
    "gender" character varying(16) NOT NULL,
    "political_status" character varying(32),
    "phone_number" character varying(32),
    "identity_no" character varying(64),
    "enrollment_year" integer NOT NULL,
    "degree_type" character varying(32) NOT NULL,
    "team_name" character varying(128),
    "current_status" character varying(32) DEFAULT 'enrolled'::character varying NOT NULL,
    "primary_advisor_id" bigint,
    "is_deleted" boolean DEFAULT false NOT NULL,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "team_id" bigint,
    "portal_student_id" bigint,
    CONSTRAINT "dtlms_students_pkey" PRIMARY KEY (id),
    CONSTRAINT "dtlms_students_student_no_key" UNIQUE (student_no)
);

-- Table: public.dtlms_system_configs
CREATE TABLE public."dtlms_system_configs" (
    "id" bigint DEFAULT nextval('dtlms_system_configs_id_seq'::regclass) NOT NULL,
    "config_key" character varying(128) NOT NULL,
    "config_value" text NOT NULL,
    "description" text,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_system_configs_pkey" PRIMARY KEY (id),
    CONSTRAINT "dtlms_system_configs_config_key_key" UNIQUE (config_key)
);

-- Table: public.dtlms_team_advisors
CREATE TABLE public."dtlms_team_advisors" (
    "id" bigint DEFAULT nextval('dtlms_team_advisors_id_seq'::regclass) NOT NULL,
    "team_id" bigint NOT NULL,
    "advisor_id" bigint NOT NULL,
    "advisor_role" character varying(32) DEFAULT 'member'::character varying NOT NULL,
    "joined_on" date,
    "left_on" date,
    "is_deleted" boolean DEFAULT false NOT NULL,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "advisor_user_id" bigint,
    CONSTRAINT "dtlms_team_advisors_pkey" PRIMARY KEY (id),
    CONSTRAINT "dtlms_team_advisors_team_id_advisor_id_key" UNIQUE (team_id, advisor_id)
);

-- Table: public.dtlms_teams
CREATE TABLE public."dtlms_teams" (
    "id" bigint DEFAULT nextval('dtlms_teams_id_seq'::regclass) NOT NULL,
    "team_code" character varying(32) NOT NULL,
    "team_name" character varying(128) NOT NULL,
    "department_name" character varying(128) NOT NULL,
    "discipline_name" character varying(128),
    "lead_advisor_id" bigint,
    "research_directions" text,
    "team_status" character varying(32) DEFAULT 'active'::character varying NOT NULL,
    "established_on" date,
    "description" text,
    "is_deleted" boolean DEFAULT false NOT NULL,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "lead_user_id" bigint,
    CONSTRAINT "dtlms_teams_pkey" PRIMARY KEY (id),
    CONSTRAINT "dtlms_teams_team_code_key" UNIQUE (team_code),
    CONSTRAINT "dtlms_teams_team_name_key" UNIQUE (team_name)
);

-- Table: public.dtlms_theses
CREATE TABLE public."dtlms_theses" (
    "id" bigint DEFAULT nextval('dtlms_theses_id_seq'::regclass) NOT NULL,
    "student_id" bigint NOT NULL,
    "advisor_id" bigint NOT NULL,
    "title" character varying(255) NOT NULL,
    "plagiarism_rate" numeric(5,2),
    "thesis_status" character varying(32) DEFAULT 'draft'::character varying NOT NULL,
    "blind_review_status" character varying(32) DEFAULT 'pending'::character varying NOT NULL,
    "defense_date" date,
    "degree_granted" character varying(32) DEFAULT 'pending'::character varying NOT NULL,
    "is_deleted" boolean DEFAULT false NOT NULL,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "business_key" character varying(64) NOT NULL,
    CONSTRAINT "dtlms_theses_pkey" PRIMARY KEY (id)
);

-- Table: public.dtlms_thesis_reviews
CREATE TABLE public."dtlms_thesis_reviews" (
    "id" bigint DEFAULT nextval('dtlms_thesis_reviews_id_seq'::regclass) NOT NULL,
    "thesis_id" bigint NOT NULL,
    "expert_name" character varying(128) NOT NULL,
    "review_score" numeric(5,2),
    "review_status" character varying(32) DEFAULT 'pending'::character varying NOT NULL,
    "review_comment" text,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_thesis_reviews_pkey" PRIMARY KEY (id)
);

-- Table: public.dtlms_training_plan_versions
CREATE TABLE public."dtlms_training_plan_versions" (
    "id" bigint DEFAULT nextval('dtlms_training_plan_versions_id_seq'::regclass) NOT NULL,
    "training_plan_id" bigint NOT NULL,
    "version_no" character varying(16) NOT NULL,
    "change_reason" text,
    "plan_snapshot" text NOT NULL,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_training_plan_versions_pkey" PRIMARY KEY (id)
);

-- Table: public.dtlms_training_plans
CREATE TABLE public."dtlms_training_plans" (
    "id" bigint DEFAULT nextval('dtlms_training_plans_id_seq'::regclass) NOT NULL,
    "student_id" bigint NOT NULL,
    "advisor_id" bigint NOT NULL,
    "version_no" character varying(16) DEFAULT 'v1.0'::character varying NOT NULL,
    "report_cycle" character varying(32) NOT NULL,
    "plan_status" character varying(32) DEFAULT 'draft'::character varying NOT NULL,
    "scientific_goal" text NOT NULL,
    "assessment_rule" text NOT NULL,
    "is_deleted" boolean DEFAULT false NOT NULL,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_training_plans_pkey" PRIMARY KEY (id)
);

-- Table: public.dtlms_user_profiles
CREATE TABLE public."dtlms_user_profiles" (
    "username" character varying(64) NOT NULL,
    "full_name" character varying(128) NOT NULL,
    "role_name" character varying(128) NOT NULL,
    "department_name" character varying(128) NOT NULL,
    "phone_number" character varying(32),
    "email" character varying(128),
    "theme_color" character varying(32) DEFAULT '#0f4cbd'::character varying NOT NULL,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "introduction" text,
    CONSTRAINT "dtlms_user_profiles_pkey" PRIMARY KEY (username)
);

-- Table: public.dtlms_user_roles
CREATE TABLE public."dtlms_user_roles" (
    "id" bigint DEFAULT nextval('dtlms_user_roles_id_seq'::regclass) NOT NULL,
    "user_id" bigint NOT NULL,
    "role_id" bigint NOT NULL,
    "grant_source" character varying(64) DEFAULT 'bootstrap'::character varying NOT NULL,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_user_roles_pkey" PRIMARY KEY (id),
    CONSTRAINT "dtlms_user_roles_user_id_role_id_key" UNIQUE (user_id, role_id)
);

-- Table: public.dtlms_users
CREATE TABLE public."dtlms_users" (
    "id" bigint DEFAULT nextval('dtlms_users_id_seq'::regclass) NOT NULL,
    "username" character varying(64) NOT NULL,
    "full_name" character varying(128) NOT NULL,
    "email" character varying(128),
    "password_hash" character varying(255) NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "is_deleted" boolean DEFAULT false NOT NULL,
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "department_name" character varying(128) DEFAULT ''::character varying NOT NULL,
    "phone_number" character varying(32),
    "last_login_at" timestamp with time zone,
    CONSTRAINT "dtlms_users_pkey" PRIMARY KEY (id),
    CONSTRAINT "dtlms_users_username_key" UNIQUE (username)
);

-- Table: public.dtlms_wf_de_model
CREATE TABLE public."dtlms_wf_de_model" (
    "id_" character varying(64) NOT NULL,
    "name_" character varying(255) NOT NULL,
    "key_" character varying(128) NOT NULL,
    "category_" character varying(128),
    "version_" integer DEFAULT 1 NOT NULL,
    "model_type_" integer DEFAULT 0 NOT NULL,
    "description_" text,
    "meta_info_" jsonb,
    "created_" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "last_updated_" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "tenant_id_" character varying(64),
    "deployment_id_" character varying(64),
    "resource_name_" character varying(255),
    "editor_source_value_" text,
    "editor_source_extra_value_" jsonb,
    CONSTRAINT "dtlms_wf_de_model_pkey" PRIMARY KEY (id_)
);

-- Table: public.dtlms_wf_hi_actinst
CREATE TABLE public."dtlms_wf_hi_actinst" (
    "id_" character varying(64) NOT NULL,
    "proc_def_id_" character varying(64) NOT NULL,
    "proc_inst_id_" character varying(64) NOT NULL,
    "exec_id_" character varying(64),
    "act_id_" character varying(128) NOT NULL,
    "act_name_" character varying(255),
    "act_type_" character varying(64) NOT NULL,
    "assignee_" character varying(64),
    "start_time_" timestamp(6) with time zone NOT NULL,
    "end_time_" timestamp(6) with time zone,
    "duration_ms_" bigint,
    "business_key_" character varying(64),
    CONSTRAINT "dtlms_wf_hi_actinst_pkey" PRIMARY KEY (id_)
);

-- Table: public.dtlms_wf_hi_procinst
CREATE TABLE public."dtlms_wf_hi_procinst" (
    "id_" character varying(64) NOT NULL,
    "proc_inst_id_" character varying(64) NOT NULL,
    "business_key_" character varying(64),
    "proc_def_id_" character varying(64) NOT NULL,
    "start_time_" timestamp(6) with time zone NOT NULL,
    "end_time_" timestamp(6) with time zone,
    "duration_ms_" bigint,
    "start_user_id_" character varying(64),
    "end_act_id_" character varying(128),
    "delete_reason_" character varying(255),
    "start_act_id_" character varying(128),
    "state_" character varying(32) DEFAULT 'ACTIVE'::character varying NOT NULL,
    CONSTRAINT "dtlms_wf_hi_procinst_pkey" PRIMARY KEY (id_),
    CONSTRAINT "dtlms_wf_hi_procinst_proc_inst_id__key" UNIQUE (proc_inst_id_)
);

-- Table: public.dtlms_wf_hi_taskinst
CREATE TABLE public."dtlms_wf_hi_taskinst" (
    "id_" character varying(64) NOT NULL,
    "task_def_key_" character varying(128),
    "proc_def_id_" character varying(64) NOT NULL,
    "proc_inst_id_" character varying(64) NOT NULL,
    "exec_id_" character varying(64),
    "name_" character varying(255) NOT NULL,
    "business_key_" character varying(64),
    "assignee_" character varying(64),
    "owner_" character varying(64),
    "start_time_" timestamp(6) with time zone NOT NULL,
    "claim_time_" timestamp(6) with time zone,
    "end_time_" timestamp(6) with time zone,
    "duration_ms_" bigint,
    "due_date_" timestamp(6) with time zone,
    "delete_reason_" character varying(255),
    "priority_" integer DEFAULT 50 NOT NULL,
    "category_" character varying(128),
    CONSTRAINT "dtlms_wf_hi_taskinst_pkey" PRIMARY KEY (id_)
);

-- Table: public.dtlms_wf_hi_varinst
CREATE TABLE public."dtlms_wf_hi_varinst" (
    "id_" character varying(128) NOT NULL,
    "proc_inst_id_" character varying(64) NOT NULL,
    "exec_id_" character varying(64),
    "task_id_" character varying(64),
    "name_" character varying(128) NOT NULL,
    "var_type_" character varying(32) NOT NULL,
    "text_value_" text,
    "number_value_" bigint,
    "json_value_" jsonb,
    "create_time_" timestamp(6) with time zone NOT NULL,
    "last_updated_time_" timestamp(6) with time zone NOT NULL,
    CONSTRAINT "dtlms_wf_hi_varinst_pkey" PRIMARY KEY (id_)
);

-- Table: public.dtlms_wf_re_deployment
CREATE TABLE public."dtlms_wf_re_deployment" (
    "id_" character varying(64) NOT NULL,
    "name_" character varying(255) NOT NULL,
    "category_" character varying(128),
    "key_" character varying(128),
    "deploy_time_" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "tenant_id_" character varying(64),
    CONSTRAINT "dtlms_wf_re_deployment_pkey" PRIMARY KEY (id_)
);

-- Table: public.dtlms_wf_re_procdef
CREATE TABLE public."dtlms_wf_re_procdef" (
    "id_" character varying(64) NOT NULL,
    "key_" character varying(128) NOT NULL,
    "version_" integer DEFAULT 1 NOT NULL,
    "deployment_id_" character varying(64),
    "resource_name_" character varying(255),
    "diagram_resource_name_" character varying(255),
    "name_" character varying(255) NOT NULL,
    "category_" character varying(128),
    "description_" text,
    "suspension_state_" integer DEFAULT 1 NOT NULL,
    "tenant_id_" character varying(64),
    CONSTRAINT "dtlms_wf_re_procdef_pkey" PRIMARY KEY (id_)
);

-- Table: public.dtlms_wf_ru_execution
CREATE TABLE public."dtlms_wf_ru_execution" (
    "id_" character varying(64) NOT NULL,
    "proc_inst_id_" character varying(64) NOT NULL,
    "proc_def_id_" character varying(64) NOT NULL,
    "business_key_" character varying(64),
    "parent_id_" character varying(64),
    "act_id_" character varying(128),
    "is_active_" boolean DEFAULT true NOT NULL,
    "is_concurrent_" boolean DEFAULT false NOT NULL,
    "is_scope_" boolean DEFAULT true NOT NULL,
    "start_time_" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "start_user_id_" character varying(64),
    "super_exec_" character varying(64),
    "tenant_id_" character varying(64),
    CONSTRAINT "dtlms_wf_ru_execution_pkey" PRIMARY KEY (id_)
);

-- Table: public.dtlms_wf_ru_identitylink
CREATE TABLE public."dtlms_wf_ru_identitylink" (
    "id_" bigint DEFAULT nextval('dtlms_wf_ru_identitylink_id__seq'::regclass) NOT NULL,
    "task_id_" character varying(64) NOT NULL,
    "proc_inst_id_" character varying(64),
    "user_id_" character varying(64),
    "group_id_" character varying(64),
    "link_type_" character varying(32) NOT NULL,
    "created_at_" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_wf_ru_identitylink_pkey" PRIMARY KEY (id_)
);

-- Table: public.dtlms_wf_ru_task
CREATE TABLE public."dtlms_wf_ru_task" (
    "id_" character varying(64) NOT NULL,
    "exec_id_" character varying(64) NOT NULL,
    "proc_inst_id_" character varying(64) NOT NULL,
    "proc_def_id_" character varying(64) NOT NULL,
    "task_def_key_" character varying(128),
    "name_" character varying(255) NOT NULL,
    "business_key_" character varying(64),
    "assignee_" character varying(64),
    "owner_" character varying(64),
    "create_time_" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "due_date_" timestamp(6) with time zone,
    "claim_time_" timestamp(6) with time zone,
    "priority_" integer DEFAULT 50 NOT NULL,
    "suspension_state_" integer DEFAULT 1 NOT NULL,
    "tenant_id_" character varying(64),
    "form_key_" character varying(255),
    "description_" text,
    CONSTRAINT "dtlms_wf_ru_task_pkey" PRIMARY KEY (id_)
);

-- Table: public.dtlms_wf_ru_variable
CREATE TABLE public."dtlms_wf_ru_variable" (
    "id_" character varying(128) NOT NULL,
    "exec_id_" character varying(64) NOT NULL,
    "proc_inst_id_" character varying(64) NOT NULL,
    "task_id_" character varying(64),
    "name_" character varying(128) NOT NULL,
    "var_type_" character varying(32) NOT NULL,
    "text_value_" text,
    "number_value_" bigint,
    "json_value_" jsonb,
    "create_time_" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_wf_ru_variable_pkey" PRIMARY KEY (id_)
);

-- Table: public.dtlms_written_exam_scores
CREATE TABLE public."dtlms_written_exam_scores" (
    "id" bigint DEFAULT nextval('dtlms_written_exam_scores_id_seq'::regclass) NOT NULL,
    "application_id" bigint NOT NULL,
    "exam_date" date,
    "exam_score" numeric(5,2),
    "import_batch_no" character varying(64),
    "created_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "dtlms_written_exam_scores_pkey" PRIMARY KEY (id)
);

ALTER TABLE public."dtlms_achievements" ADD CONSTRAINT "dtlms_achievements_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES public."dtlms_students" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_admission_decisions" ADD CONSTRAINT "dtlms_admission_decisions_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES public."dtlms_recruitment_applications" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_advisors" ADD CONSTRAINT "fk_dtlms_advisors_user_id" FOREIGN KEY ("user_id") REFERENCES public."dtlms_users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_application_materials" ADD CONSTRAINT "dtlms_application_materials_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES public."dtlms_recruitment_applications" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_background_assessments" ADD CONSTRAINT "dtlms_background_assessments_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES public."dtlms_recruitment_applications" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_dict_data" ADD CONSTRAINT "dtlms_dict_data_dict_type_id_fkey" FOREIGN KEY ("dict_type_id") REFERENCES public."dtlms_dict_types" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_interview_groups" ADD CONSTRAINT "dtlms_interview_groups_plan_id_fkey" FOREIGN KEY ("plan_id") REFERENCES public."dtlms_recruitment_plans" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_interview_schedules" ADD CONSTRAINT "dtlms_interview_schedules_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES public."dtlms_recruitment_applications" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_interview_schedules" ADD CONSTRAINT "dtlms_interview_schedules_interview_group_id_fkey" FOREIGN KEY ("interview_group_id") REFERENCES public."dtlms_interview_groups" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_interview_scores" ADD CONSTRAINT "dtlms_interview_scores_schedule_id_fkey" FOREIGN KEY ("schedule_id") REFERENCES public."dtlms_interview_schedules" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_material_scores" ADD CONSTRAINT "dtlms_material_scores_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES public."dtlms_recruitment_applications" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_material_scores" ADD CONSTRAINT "dtlms_material_scores_reviewer_assignment_id_fkey" FOREIGN KEY ("reviewer_assignment_id") REFERENCES public."dtlms_reviewer_assignments" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_outbound_studies" ADD CONSTRAINT "dtlms_outbound_studies_advisor_id_fkey" FOREIGN KEY ("advisor_id") REFERENCES public."dtlms_advisors" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_outbound_studies" ADD CONSTRAINT "dtlms_outbound_studies_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES public."dtlms_students" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_portal_application_achievement_records" ADD CONSTRAINT "dtlms_portal_application_achievement_record_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES public."dtlms_recruitment_applications" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE public."dtlms_portal_application_attachments" ADD CONSTRAINT "dtlms_portal_application_attachments_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES public."dtlms_recruitment_applications" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE public."dtlms_portal_application_attachments" ADD CONSTRAINT "dtlms_portal_application_attachments_portal_student_id_fkey" FOREIGN KEY ("portal_student_id") REFERENCES public."dtlms_portal_students" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE public."dtlms_portal_application_declarations" ADD CONSTRAINT "dtlms_portal_application_declarations_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES public."dtlms_recruitment_applications" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE public."dtlms_portal_application_education_experiences" ADD CONSTRAINT "dtlms_portal_application_education_experien_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES public."dtlms_recruitment_applications" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE public."dtlms_portal_application_english_proficiencies" ADD CONSTRAINT "dtlms_portal_application_english_proficienc_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES public."dtlms_recruitment_applications" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE public."dtlms_portal_application_family_members" ADD CONSTRAINT "dtlms_portal_application_family_members_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES public."dtlms_recruitment_applications" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE public."dtlms_portal_application_personal_statements" ADD CONSTRAINT "dtlms_portal_application_personal_statement_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES public."dtlms_recruitment_applications" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE public."dtlms_portal_application_practice_experiences" ADD CONSTRAINT "dtlms_portal_application_practice_experienc_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES public."dtlms_recruitment_applications" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE public."dtlms_portal_application_preferences" ADD CONSTRAINT "dtlms_portal_application_preferences_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES public."dtlms_recruitment_applications" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE public."dtlms_portal_application_preferences" ADD CONSTRAINT "fk_dtlms_portal_application_preferences_advisor_user_id" FOREIGN KEY ("advisor_user_id") REFERENCES public."dtlms_users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_portal_application_preferences" ADD CONSTRAINT "fk_dtlms_portal_application_preferences_team_id" FOREIGN KEY ("team_id") REFERENCES public."dtlms_teams" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_portal_student_profiles" ADD CONSTRAINT "dtlms_portal_student_profiles_portal_student_id_fkey" FOREIGN KEY ("portal_student_id") REFERENCES public."dtlms_portal_students" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE public."dtlms_portal_students" ADD CONSTRAINT "dtlms_portal_students_selected_plan_id_fkey" FOREIGN KEY ("selected_plan_id") REFERENCES public."dtlms_recruitment_plans" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_portal_students" ADD CONSTRAINT "fk_dtlms_portal_students_selected_advisor_user_id" FOREIGN KEY ("selected_advisor_user_id") REFERENCES public."dtlms_users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_portal_students" ADD CONSTRAINT "fk_dtlms_portal_students_selected_team_id" FOREIGN KEY ("selected_team_id") REFERENCES public."dtlms_teams" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_qualification_reviews" ADD CONSTRAINT "dtlms_qualification_reviews_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES public."dtlms_recruitment_applications" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_recruitment_applications" ADD CONSTRAINT "dtlms_recruitment_applications_intended_field_id_fkey" FOREIGN KEY ("intended_field_id") REFERENCES public."dtlms_research_fields" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_recruitment_applications" ADD CONSTRAINT "dtlms_recruitment_applications_plan_id_fkey" FOREIGN KEY ("plan_id") REFERENCES public."dtlms_recruitment_plans" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_recruitment_applications" ADD CONSTRAINT "dtlms_recruitment_applications_portal_student_id_fkey" FOREIGN KEY ("portal_student_id") REFERENCES public."dtlms_portal_students" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_recruitment_applications" ADD CONSTRAINT "fk_dtlms_recruitment_applications_first_choice_team_id" FOREIGN KEY ("first_choice_team_id") REFERENCES public."dtlms_teams" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_recruitment_applications" ADD CONSTRAINT "fk_dtlms_recruitment_applications_intended_advisor_user_id" FOREIGN KEY ("intended_advisor_user_id") REFERENCES public."dtlms_users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_recruitment_applications" ADD CONSTRAINT "fk_dtlms_recruitment_applications_second_choice_team_id" FOREIGN KEY ("second_choice_team_id") REFERENCES public."dtlms_teams" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_research_projects" ADD CONSTRAINT "dtlms_research_projects_principal_advisor_id_fkey" FOREIGN KEY ("principal_advisor_id") REFERENCES public."dtlms_advisors" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_reviewer_assignments" ADD CONSTRAINT "dtlms_reviewer_assignments_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES public."dtlms_recruitment_applications" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_role_permissions" ADD CONSTRAINT "dtlms_role_permissions_permission_id_fkey" FOREIGN KEY ("permission_id") REFERENCES public."dtlms_permissions" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_role_permissions" ADD CONSTRAINT "dtlms_role_permissions_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES public."dtlms_roles" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_scientific_reports" ADD CONSTRAINT "dtlms_scientific_reports_reviewer_advisor_id_fkey" FOREIGN KEY ("reviewer_advisor_id") REFERENCES public."dtlms_advisors" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_scientific_reports" ADD CONSTRAINT "dtlms_scientific_reports_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES public."dtlms_students" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_scientific_reports" ADD CONSTRAINT "dtlms_scientific_reports_training_plan_id_fkey" FOREIGN KEY ("training_plan_id") REFERENCES public."dtlms_training_plans" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_student_advisor_history" ADD CONSTRAINT "dtlms_student_advisor_history_advisor_id_fkey" FOREIGN KEY ("advisor_id") REFERENCES public."dtlms_advisors" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_student_advisor_history" ADD CONSTRAINT "dtlms_student_advisor_history_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES public."dtlms_students" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_student_team_history" ADD CONSTRAINT "dtlms_student_team_history_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES public."dtlms_students" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_student_team_history" ADD CONSTRAINT "dtlms_student_team_history_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES public."dtlms_teams" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_students" ADD CONSTRAINT "dtlms_students_primary_advisor_id_fkey" FOREIGN KEY ("primary_advisor_id") REFERENCES public."dtlms_advisors" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_students" ADD CONSTRAINT "dtlms_students_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES public."dtlms_teams" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_students" ADD CONSTRAINT "fk_dtlms_students_portal_student_id" FOREIGN KEY ("portal_student_id") REFERENCES public."dtlms_portal_students" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_team_advisors" ADD CONSTRAINT "dtlms_team_advisors_advisor_id_fkey" FOREIGN KEY ("advisor_id") REFERENCES public."dtlms_advisors" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_team_advisors" ADD CONSTRAINT "dtlms_team_advisors_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES public."dtlms_teams" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_team_advisors" ADD CONSTRAINT "fk_dtlms_team_advisors_advisor_user_id" FOREIGN KEY ("advisor_user_id") REFERENCES public."dtlms_users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_teams" ADD CONSTRAINT "dtlms_teams_lead_advisor_id_fkey" FOREIGN KEY ("lead_advisor_id") REFERENCES public."dtlms_advisors" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_teams" ADD CONSTRAINT "fk_dtlms_teams_lead_user_id" FOREIGN KEY ("lead_user_id") REFERENCES public."dtlms_users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_theses" ADD CONSTRAINT "dtlms_theses_advisor_id_fkey" FOREIGN KEY ("advisor_id") REFERENCES public."dtlms_advisors" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_theses" ADD CONSTRAINT "dtlms_theses_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES public."dtlms_students" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_thesis_reviews" ADD CONSTRAINT "dtlms_thesis_reviews_thesis_id_fkey" FOREIGN KEY ("thesis_id") REFERENCES public."dtlms_theses" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_training_plan_versions" ADD CONSTRAINT "dtlms_training_plan_versions_training_plan_id_fkey" FOREIGN KEY ("training_plan_id") REFERENCES public."dtlms_training_plans" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_training_plans" ADD CONSTRAINT "dtlms_training_plans_advisor_id_fkey" FOREIGN KEY ("advisor_id") REFERENCES public."dtlms_advisors" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_training_plans" ADD CONSTRAINT "dtlms_training_plans_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES public."dtlms_students" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_user_profiles" ADD CONSTRAINT "dtlms_user_profiles_username_fkey" FOREIGN KEY ("username") REFERENCES public."dtlms_users" ("username") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE public."dtlms_user_roles" ADD CONSTRAINT "dtlms_user_roles_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES public."dtlms_roles" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_user_roles" ADD CONSTRAINT "dtlms_user_roles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES public."dtlms_users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_wf_hi_actinst" ADD CONSTRAINT "dtlms_wf_hi_actinst_proc_def_id__fkey" FOREIGN KEY ("proc_def_id_") REFERENCES public."dtlms_wf_re_procdef" ("id_") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_wf_hi_procinst" ADD CONSTRAINT "dtlms_wf_hi_procinst_proc_def_id__fkey" FOREIGN KEY ("proc_def_id_") REFERENCES public."dtlms_wf_re_procdef" ("id_") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_wf_hi_taskinst" ADD CONSTRAINT "dtlms_wf_hi_taskinst_proc_def_id__fkey" FOREIGN KEY ("proc_def_id_") REFERENCES public."dtlms_wf_re_procdef" ("id_") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_wf_re_procdef" ADD CONSTRAINT "dtlms_wf_re_procdef_deployment_id__fkey" FOREIGN KEY ("deployment_id_") REFERENCES public."dtlms_wf_re_deployment" ("id_") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_wf_ru_execution" ADD CONSTRAINT "dtlms_wf_ru_execution_proc_def_id__fkey" FOREIGN KEY ("proc_def_id_") REFERENCES public."dtlms_wf_re_procdef" ("id_") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_wf_ru_task" ADD CONSTRAINT "dtlms_wf_ru_task_exec_id__fkey" FOREIGN KEY ("exec_id_") REFERENCES public."dtlms_wf_ru_execution" ("id_") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_wf_ru_task" ADD CONSTRAINT "dtlms_wf_ru_task_proc_def_id__fkey" FOREIGN KEY ("proc_def_id_") REFERENCES public."dtlms_wf_re_procdef" ("id_") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_wf_ru_variable" ADD CONSTRAINT "dtlms_wf_ru_variable_exec_id__fkey" FOREIGN KEY ("exec_id_") REFERENCES public."dtlms_wf_ru_execution" ("id_") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE public."dtlms_written_exam_scores" ADD CONSTRAINT "dtlms_written_exam_scores_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES public."dtlms_recruitment_applications" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

CREATE INDEX idx_admission_decision_status ON public.dtlms_admission_decisions USING btree (decision_status);

CREATE UNIQUE INDEX idx_dtlms_advisors_user_id ON public.dtlms_advisors USING btree (user_id) WHERE (user_id IS NOT NULL);

CREATE INDEX idx_background_assessment_application ON public.dtlms_background_assessments USING btree (application_id, assessed_at DESC);
CREATE INDEX idx_background_assessment_result ON public.dtlms_background_assessments USING btree (assessment_result);

CREATE INDEX idx_sync_logs_source_target ON public.dtlms_data_sync_logs USING btree (source_system, target_system, created_at);

CREATE INDEX idx_dtlms_dict_data_type_sort ON public.dtlms_dict_data USING btree (dict_type, sort_order, id);

CREATE INDEX idx_interview_schedule_time ON public.dtlms_interview_schedules USING btree (starts_at, ends_at);

CREATE INDEX idx_notification_delivery_logs_channel_time ON public.dtlms_notification_delivery_logs USING btree (channel, created_at);
CREATE INDEX idx_notification_delivery_logs_recipient ON public.dtlms_notification_delivery_logs USING btree (recipient);
CREATE INDEX idx_notification_delivery_logs_status_time ON public.dtlms_notification_delivery_logs USING btree (send_status, created_at);

CREATE INDEX idx_operation_logs_entity ON public.dtlms_operation_logs USING btree (entity_name, entity_id);
CREATE INDEX idx_operation_logs_module_time ON public.dtlms_operation_logs USING btree (module_name, created_at);

CREATE INDEX idx_outbound_studies_status ON public.dtlms_outbound_studies USING btree (approval_status);
CREATE UNIQUE INDEX ux_dtlms_outbound_studies_business_key ON public.dtlms_outbound_studies USING btree (business_key);

CREATE INDEX idx_portal_application_achievement_application ON public.dtlms_portal_application_achievement_records USING btree (application_id, achievement_type);

CREATE INDEX idx_portal_application_attachment_owner ON public.dtlms_portal_application_attachments USING btree (application_id, owner_type, owner_id);

CREATE INDEX idx_portal_application_education_application ON public.dtlms_portal_application_education_experiences USING btree (application_id, sort_order);

CREATE INDEX idx_portal_application_english_application ON public.dtlms_portal_application_english_proficiencies USING btree (application_id);

CREATE INDEX idx_portal_application_family_application ON public.dtlms_portal_application_family_members USING btree (application_id);
CREATE UNIQUE INDEX ux_portal_application_family_parent_unique ON public.dtlms_portal_application_family_members USING btree (application_id, relation_type) WHERE ((relation_type)::text = ANY (ARRAY[('父亲'::character varying)::text, ('母亲'::character varying)::text]));

CREATE INDEX idx_portal_application_practice_application ON public.dtlms_portal_application_practice_experiences USING btree (application_id);

CREATE INDEX idx_dtlms_portal_application_preferences_team_id ON public.dtlms_portal_application_preferences USING btree (team_id) WHERE (team_id IS NOT NULL);
CREATE INDEX idx_portal_application_preferences_application ON public.dtlms_portal_application_preferences USING btree (application_id, preference_order);

CREATE INDEX idx_dtlms_portal_students_selected_team_id ON public.dtlms_portal_students USING btree (selected_team_id) WHERE (selected_team_id IS NOT NULL);

CREATE INDEX idx_applications_plan_status ON public.dtlms_recruitment_applications USING btree (plan_id, application_status);
CREATE INDEX idx_applications_portal_student ON public.dtlms_recruitment_applications USING btree (portal_student_id);
CREATE INDEX idx_dtlms_recruitment_applications_email ON public.dtlms_recruitment_applications USING btree (email);
CREATE INDEX idx_dtlms_recruitment_applications_first_choice_team_id ON public.dtlms_recruitment_applications USING btree (first_choice_team_id) WHERE (first_choice_team_id IS NOT NULL);
CREATE INDEX idx_dtlms_recruitment_applications_phone_number ON public.dtlms_recruitment_applications USING btree (phone_number);
CREATE UNIQUE INDEX ux_dtlms_recruitment_applications_business_key ON public.dtlms_recruitment_applications USING btree (business_key);

CREATE INDEX idx_reports_student_period ON public.dtlms_scientific_reports USING btree (student_id, period_label);
CREATE UNIQUE INDEX ux_dtlms_scientific_reports_business_key ON public.dtlms_scientific_reports USING btree (business_key);

CREATE UNIQUE INDEX idx_dtlms_students_portal_student_id ON public.dtlms_students USING btree (portal_student_id) WHERE (portal_student_id IS NOT NULL);
CREATE INDEX idx_students_primary_advisor ON public.dtlms_students USING btree (primary_advisor_id);
CREATE INDEX idx_students_status ON public.dtlms_students USING btree (current_status);

CREATE UNIQUE INDEX idx_dtlms_team_advisors_team_user ON public.dtlms_team_advisors USING btree (team_id, advisor_user_id) WHERE (advisor_user_id IS NOT NULL);

CREATE INDEX idx_dtlms_teams_lead_user_id ON public.dtlms_teams USING btree (lead_user_id) WHERE (lead_user_id IS NOT NULL);

CREATE INDEX idx_thesis_status ON public.dtlms_theses USING btree (thesis_status);
CREATE UNIQUE INDEX ux_dtlms_theses_business_key ON public.dtlms_theses USING btree (business_key);

CREATE INDEX idx_training_plan_student ON public.dtlms_training_plans USING btree (student_id);

CREATE INDEX idx_dtlms_wf_hi_actinst_proc_inst ON public.dtlms_wf_hi_actinst USING btree (proc_inst_id_);

CREATE INDEX idx_dtlms_wf_hi_procinst_business_key ON public.dtlms_wf_hi_procinst USING btree (business_key_);

CREATE INDEX idx_dtlms_wf_hi_taskinst_proc_inst ON public.dtlms_wf_hi_taskinst USING btree (proc_inst_id_);

CREATE INDEX idx_dtlms_wf_hi_varinst_proc_inst ON public.dtlms_wf_hi_varinst USING btree (proc_inst_id_);

CREATE INDEX idx_dtlms_wf_re_procdef_key ON public.dtlms_wf_re_procdef USING btree (key_);

CREATE INDEX idx_dtlms_wf_ru_execution_proc_inst ON public.dtlms_wf_ru_execution USING btree (proc_inst_id_);

CREATE INDEX idx_dtlms_wf_ru_task_business_key ON public.dtlms_wf_ru_task USING btree (business_key_);
CREATE INDEX idx_dtlms_wf_ru_task_proc_inst ON public.dtlms_wf_ru_task USING btree (proc_inst_id_);
