ALTER TABLE dtlms_recruitment_applications
    ADD COLUMN IF NOT EXISTS review_round VARCHAR(64),
    ADD COLUMN IF NOT EXISTS first_choice VARCHAR(255),
    ADD COLUMN IF NOT EXISTS second_choice VARCHAR(255),
    ADD COLUMN IF NOT EXISTS political_status VARCHAR(64),
    ADD COLUMN IF NOT EXISTS marital_status VARCHAR(32),
    ADD COLUMN IF NOT EXISTS religious_belief VARCHAR(128),
    ADD COLUMN IF NOT EXISTS native_place VARCHAR(128),
    ADD COLUMN IF NOT EXISTS phone_number VARCHAR(64),
    ADD COLUMN IF NOT EXISTS email VARCHAR(255),
    ADD COLUMN IF NOT EXISTS mailing_address TEXT,
    ADD COLUMN IF NOT EXISTS id_type VARCHAR(64),
    ADD COLUMN IF NOT EXISTS id_number VARCHAR(128),
    ADD COLUMN IF NOT EXISTS undergraduate_school VARCHAR(255),
    ADD COLUMN IF NOT EXISTS accept_adjustment VARCHAR(16),
    ADD COLUMN IF NOT EXISTS undergraduate_average_score VARCHAR(64),
    ADD COLUMN IF NOT EXISTS undergraduate_gpa VARCHAR(64),
    ADD COLUMN IF NOT EXISTS undergraduate_rank VARCHAR(64),
    ADD COLUMN IF NOT EXISTS undergraduate_major VARCHAR(255),
    ADD COLUMN IF NOT EXISTS graduate_average_score VARCHAR(64),
    ADD COLUMN IF NOT EXISTS graduate_gpa VARCHAR(64),
    ADD COLUMN IF NOT EXISTS graduate_rank VARCHAR(64),
    ADD COLUMN IF NOT EXISTS graduate_major VARCHAR(255),
    ADD COLUMN IF NOT EXISTS intended_advisor_name VARCHAR(128),
    ADD COLUMN IF NOT EXISTS discovery_channel TEXT,
    ADD COLUMN IF NOT EXISTS graduate_school VARCHAR(255),
    ADD COLUMN IF NOT EXISTS overseas_university_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS overseas_master_university_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS self_evaluation TEXT,
    ADD COLUMN IF NOT EXISTS applied_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS research_problem TEXT,
    ADD COLUMN IF NOT EXISTS research_status_analysis TEXT,
    ADD COLUMN IF NOT EXISTS research_impact TEXT,
    ADD COLUMN IF NOT EXISTS ai_society_impact TEXT,
    ADD COLUMN IF NOT EXISTS dissenting_view TEXT,
    ADD COLUMN IF NOT EXISTS family_info TEXT,
    ADD COLUMN IF NOT EXISTS education_experience TEXT,
    ADD COLUMN IF NOT EXISTS practice_experience TEXT,
    ADD COLUMN IF NOT EXISTS personal_statement_text TEXT,
    ADD COLUMN IF NOT EXISTS student_activity_experience TEXT,
    ADD COLUMN IF NOT EXISTS personal_statement_attachment TEXT,
    ADD COLUMN IF NOT EXISTS material_list_attachment TEXT,
    ADD COLUMN IF NOT EXISTS supplementary_profile TEXT;

CREATE INDEX IF NOT EXISTS idx_dtlms_recruitment_applications_phone_number
    ON dtlms_recruitment_applications (phone_number);

CREATE INDEX IF NOT EXISTS idx_dtlms_recruitment_applications_email
    ON dtlms_recruitment_applications (email);