CREATE TABLE IF NOT EXISTS dtlms_dict_types (
    id BIGSERIAL PRIMARY KEY,
    dict_name VARCHAR(100) NOT NULL,
    dict_type VARCHAR(100) NOT NULL UNIQUE,
    status VARCHAR(32) NOT NULL DEFAULT '启用',
    remark TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (status IN ('启用', '停用'))
);

CREATE TABLE IF NOT EXISTS dtlms_dict_data (
    id BIGSERIAL PRIMARY KEY,
    dict_type_id BIGINT NOT NULL REFERENCES dtlms_dict_types(id),
    dict_type VARCHAR(100) NOT NULL,
    label VARCHAR(100) NOT NULL,
    value VARCHAR(100) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT '启用',
    color_type VARCHAR(32),
    css_class VARCHAR(128),
    remark TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (dict_type, value),
    CHECK (status IN ('启用', '停用'))
);

CREATE INDEX IF NOT EXISTS idx_dtlms_dict_data_type_sort ON dtlms_dict_data(dict_type, sort_order, id);

INSERT INTO dtlms_dict_types (dict_name, dict_type, status, remark)
VALUES
    ('账号状态', 'system_account_status', '启用', '系统账号状态字典'),
    ('角色范围', 'system_role_scope', '启用', '系统角色范围字典'),
    ('集成方向', 'system_integration_direction', '启用', '系统集成方向字典'),
    ('集成频率', 'system_integration_cadence', '启用', '系统集成频率字典'),
    ('集成状态', 'system_integration_status', '启用', '系统集成状态字典'),
    ('审计策略状态', 'system_audit_status', '启用', '审计策略状态字典'),
    ('操作结果', 'system_operation_result', '启用', '操作日志结果字典'),
    ('同步状态', 'system_sync_status', '启用', '同步日志状态字典'),
    ('学生状态', 'student_status', '启用', '学生生命周期状态字典'),
    ('学位类型', 'student_degree_type', '启用', '博士类型字典'),
    ('团队状态', 'student_team_status', '启用', '团队状态字典'),
    ('政治面貌', 'student_political_status', '启用', '学生政治面貌字典'),
    ('招生学期', 'recruitment_semester', '启用', '招生学期字典'),
    ('招生计划阶段', 'recruitment_plan_stage', '启用', '招生计划阶段字典'),
    ('报考学历', 'recruitment_degree', '启用', '招生学历字典'),
    ('材料状态', 'recruitment_material_status', '启用', '材料状态字典'),
    ('申请状态', 'recruitment_application_status', '启用', '申请状态字典'),
    ('培养方案状态', 'training_plan_status', '启用', '培养方案状态字典'),
    ('科研报告周期', 'training_report_cycle', '启用', '科研报告周期字典'),
    ('科研报告状态', 'training_report_status', '启用', '科研报告状态字典'),
    ('外出研修类型', 'training_outbound_study_type', '启用', '外出研修类型字典'),
    ('外出研修审批状态', 'training_outbound_approval_status', '启用', '外出研修审批状态字典'),
    ('论文状态', 'degree_thesis_status', '启用', '论文流程状态字典'),
    ('盲审状态', 'degree_blind_review_status', '启用', '盲审状态字典'),
    ('答辩状态', 'degree_defense_status', '启用', '答辩状态字典'),
    ('授位状态', 'degree_status', '启用', '授位状态字典'),
    ('评审状态', 'degree_review_status', '启用', '评审状态字典'),
    ('流程优先级', 'workflow_priority', '启用', '审批优先级字典'),
    ('流程状态', 'workflow_status', '启用', '审批状态字典')
ON CONFLICT (dict_type) DO UPDATE SET
    dict_name = EXCLUDED.dict_name,
    status = EXCLUDED.status,
    remark = EXCLUDED.remark,
    updated_at = CURRENT_TIMESTAMP;

WITH seed_data(dict_type, label, value, sort_order, status, color_type, css_class, remark) AS (
    VALUES
        ('system_account_status', '启用', '启用', 10, '启用', 'success', NULL, NULL),
        ('system_account_status', '停用', '停用', 20, '启用', 'info', NULL, NULL),
        ('system_account_status', '锁定', '锁定', 30, '启用', 'danger', NULL, NULL),
        ('system_role_scope', '系统治理', '系统治理', 10, '启用', NULL, NULL, NULL),
        ('system_role_scope', '招生管理', '招生管理', 20, '启用', NULL, NULL, NULL),
        ('system_role_scope', '学生管理', '学生管理', 30, '启用', NULL, NULL, NULL),
        ('system_role_scope', '培养与学位', '培养与学位', 40, '启用', NULL, NULL, NULL),
        ('system_role_scope', '学位管理', '学位管理', 50, '启用', NULL, NULL, NULL),
        ('system_role_scope', '跨部门协同', '跨部门协同', 60, '启用', NULL, NULL, NULL),
        ('system_integration_direction', '主数据导入 / 录取回传', '主数据导入 / 录取回传', 10, '启用', NULL, NULL, NULL),
        ('system_integration_direction', '考勤 / 门禁 / 请假同步', '考勤 / 门禁 / 请假同步', 20, '启用', NULL, NULL, NULL),
        ('system_integration_direction', '待办通知 / 审批提醒 / 回执', '待办通知 / 审批提醒 / 回执', 30, '启用', NULL, NULL, NULL),
        ('system_integration_direction', '双向同步', '双向同步', 40, '启用', NULL, NULL, NULL),
        ('system_integration_direction', '主数据下发', '主数据下发', 50, '启用', NULL, NULL, NULL),
        ('system_integration_cadence', '实时', '实时', 10, '启用', NULL, NULL, NULL),
        ('system_integration_cadence', '实时 + 每日对账', '实时 + 每日对账', 20, '启用', NULL, NULL, NULL),
        ('system_integration_cadence', '实时事件 + 定时补偿', '实时事件 + 定时补偿', 30, '启用', NULL, NULL, NULL),
        ('system_integration_cadence', '每小时', '每小时', 40, '启用', NULL, NULL, NULL),
        ('system_integration_cadence', '每日', '每日', 50, '启用', NULL, NULL, NULL),
        ('system_integration_status', '正常', '正常', 10, '启用', 'success', NULL, NULL),
        ('system_integration_status', '告警', '告警', 20, '启用', 'warning', NULL, NULL),
        ('system_integration_status', '停用', '停用', 30, '启用', 'info', NULL, NULL),
        ('system_audit_status', '启用', '启用', 10, '启用', 'success', NULL, NULL),
        ('system_audit_status', '停用', '停用', 20, '启用', 'info', NULL, NULL),
        ('system_operation_result', '成功', 'success', 10, '启用', 'success', NULL, NULL),
        ('system_operation_result', '失败', 'failed', 20, '启用', 'danger', NULL, NULL),
        ('system_sync_status', '成功', 'success', 10, '启用', 'success', NULL, NULL),
        ('system_sync_status', '失败', 'failed', 20, '启用', 'danger', NULL, NULL),
        ('student_status', '在校', '在校', 10, '启用', 'success', NULL, NULL),
        ('student_status', '实习中', '实习中', 20, '启用', 'warning', NULL, NULL),
        ('student_status', '外出研修', '外出研修', 30, '启用', 'warning', NULL, NULL),
        ('student_status', '请假中', '请假中', 40, '启用', 'danger', NULL, NULL),
        ('student_status', '学位论文阶段', '学位论文阶段', 50, '启用', 'success', NULL, NULL),
        ('student_status', '已毕业', '已毕业', 60, '启用', 'info', NULL, NULL),
        ('student_degree_type', '工程博士', '工程博士', 10, '启用', NULL, NULL, NULL),
        ('student_degree_type', '学术博士', '学术博士', 20, '启用', NULL, NULL, NULL),
        ('student_team_status', '启用', '启用', 10, '启用', 'success', NULL, NULL),
        ('student_team_status', '筹建', '筹建', 20, '启用', 'warning', NULL, NULL),
        ('student_team_status', '停用', '停用', 30, '启用', 'info', NULL, NULL),
        ('student_political_status', '中共党员', '中共党员', 10, '启用', NULL, NULL, NULL),
        ('student_political_status', '中共预备党员', '中共预备党员', 20, '启用', NULL, NULL, NULL),
        ('student_political_status', '共青团员', '共青团员', 30, '启用', NULL, NULL, NULL),
        ('student_political_status', '群众', '群众', 40, '启用', NULL, NULL, NULL),
        ('recruitment_semester', '春', '春', 10, '启用', NULL, NULL, NULL),
        ('recruitment_semester', '秋', '秋', 20, '启用', NULL, NULL, NULL),
        ('recruitment_plan_stage', '报名配置', '报名配置', 10, '启用', NULL, NULL, NULL),
        ('recruitment_plan_stage', '资格审核', '资格审核', 20, '启用', NULL, NULL, NULL),
        ('recruitment_plan_stage', '评分推荐', '评分推荐', 30, '启用', NULL, NULL, NULL),
        ('recruitment_plan_stage', '材料评分', '材料评分', 40, '启用', NULL, NULL, NULL),
        ('recruitment_plan_stage', '面试执行', '面试执行', 50, '启用', NULL, NULL, NULL),
        ('recruitment_plan_stage', '预录取', '预录取', 60, '启用', NULL, NULL, NULL),
        ('recruitment_degree', '本科', '本科', 10, '启用', NULL, NULL, NULL),
        ('recruitment_degree', '硕士', '硕士', 20, '启用', NULL, NULL, NULL),
        ('recruitment_degree', '博士', '博士', 30, '启用', NULL, NULL, NULL),
        ('recruitment_material_status', '材料齐全', '材料齐全', 10, '启用', 'success', NULL, NULL),
        ('recruitment_material_status', '待补材料', '待补材料', 20, '启用', 'warning', NULL, NULL),
        ('recruitment_material_status', '已退回修改', '已退回修改', 30, '启用', 'danger', NULL, NULL),
        ('recruitment_application_status', '报名已提交', '报名已提交', 10, '启用', 'info', NULL, NULL),
        ('recruitment_application_status', '资格审核通过', '资格审核通过', 20, '启用', 'warning', NULL, NULL),
        ('recruitment_application_status', '材料评分中', '材料评分中', 30, '启用', 'warning', NULL, NULL),
        ('recruitment_application_status', '面试待安排', '面试待安排', 40, '启用', 'warning', NULL, NULL),
        ('recruitment_application_status', '面试完成', '面试完成', 50, '启用', 'warning', NULL, NULL),
        ('recruitment_application_status', '预录取', '预录取', 60, '启用', 'success', NULL, NULL),
        ('recruitment_application_status', '同意录取', '同意录取', 70, '启用', 'success', NULL, NULL),
        ('recruitment_application_status', '不录取', '不录取', 80, '启用', 'danger', NULL, NULL),
        ('training_plan_status', '待学生确认', '待学生确认', 10, '启用', 'warning', NULL, NULL),
        ('training_plan_status', '执行中', '执行中', 20, '启用', 'success', NULL, NULL),
        ('training_plan_status', '已归档', '已归档', 30, '启用', 'info', NULL, NULL),
        ('training_report_cycle', '月度', '月度', 10, '启用', NULL, NULL, NULL),
        ('training_report_cycle', '双月', '双月', 20, '启用', NULL, NULL, NULL),
        ('training_report_cycle', '季度', '季度', 30, '启用', NULL, NULL, NULL),
        ('training_report_cycle', '半年度', '半年度', 40, '启用', NULL, NULL, NULL),
        ('training_report_status', '待导师审阅', '待导师审阅', 10, '启用', 'warning', NULL, NULL),
        ('training_report_status', '已通过', '已通过', 20, '启用', 'success', NULL, NULL),
        ('training_report_status', '退回修改', '退回修改', 30, '启用', 'danger', NULL, NULL),
        ('training_outbound_study_type', '联合培养', '联合培养', 10, '启用', NULL, NULL, NULL),
        ('training_outbound_study_type', '企业研修', '企业研修', 20, '启用', NULL, NULL, NULL),
        ('training_outbound_study_type', '访学交流', '访学交流', 30, '启用', NULL, NULL, NULL),
        ('training_outbound_study_type', '学术会议', '学术会议', 40, '启用', NULL, NULL, NULL),
        ('training_outbound_approval_status', '审批中', '审批中', 10, '启用', 'warning', NULL, NULL),
        ('training_outbound_approval_status', '已批准', '已批准', 20, '启用', 'success', NULL, NULL),
        ('training_outbound_approval_status', '研修中', '研修中', 30, '启用', 'success', NULL, NULL),
        ('training_outbound_approval_status', '已结束', '已结束', 40, '启用', 'info', NULL, NULL),
        ('training_outbound_approval_status', '已驳回', '已驳回', 50, '启用', 'danger', NULL, NULL),
        ('degree_thesis_status', '待查重', '待查重', 10, '启用', 'warning', NULL, NULL),
        ('degree_thesis_status', '查重中', '查重中', 20, '启用', 'warning', NULL, NULL),
        ('degree_thesis_status', '查重通过', '查重通过', 30, '启用', 'success', NULL, NULL),
        ('degree_thesis_status', '退回修改', '退回修改', 40, '启用', 'danger', NULL, NULL),
        ('degree_thesis_status', '盲审通过', '盲审通过', 50, '启用', 'success', NULL, NULL),
        ('degree_blind_review_status', '待送审', '待送审', 10, '启用', 'warning', NULL, NULL),
        ('degree_blind_review_status', '未送审', '未送审', 20, '启用', 'info', NULL, NULL),
        ('degree_blind_review_status', '进行中', '进行中', 30, '启用', 'warning', NULL, NULL),
        ('degree_blind_review_status', '已通过', '已通过', 40, '启用', 'success', NULL, NULL),
        ('degree_blind_review_status', '未通过', '未通过', 50, '启用', 'danger', NULL, NULL),
        ('degree_defense_status', '未进入', '未进入', 10, '启用', 'info', NULL, NULL),
        ('degree_defense_status', '待安排', '待安排', 20, '启用', 'warning', NULL, NULL),
        ('degree_defense_status', '预答辩完成', '预答辩完成', 30, '启用', 'success', NULL, NULL),
        ('degree_defense_status', '正式答辩完成', '正式答辩完成', 40, '启用', 'success', NULL, NULL),
        ('degree_status', '待申请', '待申请', 10, '启用', 'info', NULL, NULL),
        ('degree_status', '未授位', '未授位', 20, '启用', 'danger', NULL, NULL),
        ('degree_status', '授位审批中', '授位审批中', 30, '启用', 'warning', NULL, NULL),
        ('degree_status', '待正式答辩', '待正式答辩', 40, '启用', 'warning', NULL, NULL),
        ('degree_status', '已授位', '已授位', 50, '启用', 'success', NULL, NULL),
        ('degree_review_status', '待反馈', '待反馈', 10, '启用', 'warning', NULL, NULL),
        ('degree_review_status', '已提交', '已提交', 20, '启用', 'info', NULL, NULL),
        ('degree_review_status', '已通过', '已通过', 30, '启用', 'success', NULL, NULL),
        ('degree_review_status', '需修改', '需修改', 40, '启用', 'danger', NULL, NULL),
        ('workflow_priority', '高', '高', 10, '启用', 'danger', NULL, NULL),
        ('workflow_priority', '中', '中', 20, '启用', 'warning', NULL, NULL),
        ('workflow_priority', '低', '低', 30, '启用', 'info', NULL, NULL),
        ('workflow_status', '待处理', '待处理', 10, '启用', 'warning', NULL, NULL),
        ('workflow_status', '处理中', '处理中', 20, '启用', 'warning', NULL, NULL),
        ('workflow_status', '已通过', '已通过', 30, '启用', 'success', NULL, NULL),
        ('workflow_status', '已驳回', '已驳回', 40, '启用', 'danger', NULL, NULL)
)
INSERT INTO dtlms_dict_data (dict_type_id, dict_type, label, value, sort_order, status, color_type, css_class, remark)
SELECT t.id, s.dict_type, s.label, s.value, s.sort_order, s.status, s.color_type, s.css_class, s.remark
FROM seed_data s
JOIN dtlms_dict_types t ON t.dict_type = s.dict_type
ON CONFLICT (dict_type, value) DO UPDATE SET
    label = EXCLUDED.label,
    sort_order = EXCLUDED.sort_order,
    status = EXCLUDED.status,
    color_type = EXCLUDED.color_type,
    css_class = EXCLUDED.css_class,
    remark = EXCLUDED.remark,
    dict_type_id = EXCLUDED.dict_type_id,
    updated_at = CURRENT_TIMESTAMP;