-- ============================================================
-- 脚本名称: update20260620_1.sql
-- 脚本说明: 在生产环境创建 dtlms_team_leaders 表
--           - 用于支持研究中心多负责人特性 (从单值 lead_user_id 改为多值)
--           - 字段: id, team_id, user_id, created_at, updated_at
--           - 约束: PK(id), UNIQUE(team_id, user_id), FK(team_id) -> dtlms_teams(id), FK(user_id) -> dtlms_users(id)
--           - 索引: PK, UNIQUE, idx_team_id, idx_user_id
--
-- 前置条件:
--           - dtlms_teams 表已存在
--           - dtlms_users 表已存在
--           - dtlms_teams.lead_user_id 字段保留不动（数据库层兼容）
--
-- 后续脚本:
--           - update20260619_4.sql: 从 dtlms_teams.lead_user_id 灌入初始数据
--           - update20260620.sql:  camp-offers 范围过滤规则升级
--
-- 作    者: Codex (auto)
-- 创建日期: 2026-06-20
-- ============================================================

BEGIN;

-- ============================================================
-- 1. 幂等保护: 如果表已存在, 跳过创建
-- ============================================================
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'dtlms_team_leaders'
    ) THEN
        RAISE NOTICE 'dtlms_team_leaders 表已存在, 跳过 CREATE TABLE 步骤';
    ELSE
        -- ============================================================
        -- 2. 创建表
        -- ============================================================
        CREATE TABLE public.dtlms_team_leaders (
            id          BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 1 MINVALUE 1),
            team_id     BIGINT       NOT NULL,
            user_id     BIGINT       NOT NULL,
            created_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

            CONSTRAINT dtlms_team_leaders_pkey PRIMARY KEY (id),
            CONSTRAINT dtlms_team_leaders_team_id_user_id_key UNIQUE (team_id, user_id),

            CONSTRAINT fk_dtlms_team_leaders_team_id
                FOREIGN KEY (team_id) REFERENCES public.dtlms_teams (id)
                NOT VALID,
            CONSTRAINT fk_dtlms_team_leaders_user_id
                FOREIGN KEY (user_id) REFERENCES public.dtlms_users (id)
                NOT VALID
        );

        -- ============================================================
        -- 3. 创建索引
        -- ============================================================
        CREATE INDEX idx_dtlms_team_leaders_team_id
            ON public.dtlms_team_leaders USING BTREE (team_id);
        CREATE INDEX idx_dtlms_team_leaders_user_id
            ON public.dtlms_team_leaders USING BTREE (user_id);

        RAISE NOTICE 'dtlms_team_leaders 表已创建';
    END IF;
END
$$;

-- ============================================================
-- 4. 验证: 显示表结构
-- ============================================================
SELECT
    column_name,
    data_type,
    is_nullable,
    column_default
  FROM information_schema.columns
 WHERE table_schema = 'public' AND table_name = 'dtlms_team_leaders'
 ORDER BY ordinal_position;

-- ============================================================
-- 5. 验证: 显示约束
-- ============================================================
SELECT
    conname        AS constraint_name,
    contype        AS constraint_type,
    pg_get_constraintdef(oid) AS definition
  FROM pg_constraint
 WHERE conrelid = 'public.dtlms_team_leaders'::regclass
 ORDER BY conname;

-- ============================================================
-- 6. 验证: 显示索引
-- ============================================================
SELECT
    indexname  AS index_name,
    indexdef   AS definition
  FROM pg_indexes
 WHERE schemaname = 'public' AND tablename = 'dtlms_team_leaders'
 ORDER BY indexname;

COMMIT;