import sys
sys.path.insert(0, r'D:\pyproj\pyams\backend\venv\Lib\site-packages')
import psycopg2
conn = psycopg2.connect(host='47.117.107.23',port=15431,user='postgres',password='Pass@@word123!',dbname='test061502',connect_timeout=10)
cur = conn.cursor()
cur.execute("SELECT count(*) FROM pg_type t JOIN pg_namespace n ON n.oid=t.typnamespace WHERE n.nspname='public' AND t.typtype='d'")
print('domains:', cur.fetchone()[0])
cur.execute("SELECT count(*) FROM pg_type t JOIN pg_namespace n ON n.oid=t.typnamespace WHERE n.nspname='public' AND t.typtype='e'")
print('enums:', cur.fetchone()[0])
cur.execute("SELECT count(*) FROM pg_type t JOIN pg_namespace n ON n.oid=t.typnamespace WHERE n.nspname='public' AND t.typtype='c' AND t.typrelid<>0 AND (SELECT relkind FROM pg_class WHERE oid=t.typrelid)='c'")
print('composite-types:', cur.fetchone()[0])
cur.execute("SELECT count(*) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE c.relkind IN ('r','p') AND n.nspname='public'")
print('tables:', cur.fetchone()[0])
cur.execute("SELECT count(*) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE c.relkind='S' AND n.nspname='public'")
print('sequences:', cur.fetchone()[0])
cur.execute("SELECT count(*) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE c.relkind IN ('v','m') AND n.nspname='public'")
print('views:', cur.fetchone()[0])
cur.execute("SELECT count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.prokind IN ('f','p')")
print('routines:', cur.fetchone()[0])
cur.execute("SELECT count(*) FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE NOT t.tgisinternal AND n.nspname='public'")
print('triggers:', cur.fetchone()[0])
cur.execute("SELECT count(*) FROM pg_extension e JOIN pg_namespace n ON n.oid=e.extnamespace WHERE n.nspname NOT IN ('pg_catalog')")
print('extensions:', cur.fetchone()[0])
